### ISSUE TITLE
Compilation failed under C++20

### ISSUE THREAD

**Issue by expnkx** [boostorg/format#73] opened 2020-04-09 02:58 UTC
/usr/local/include/boost/format/alt_sstream_impl.hpp:261:45: error: no matching function for call to ‘std::allocator<cha
r>::allocate(std::size_t&, char*)’
  261 |                     newptr = alloc_.allocate(new_size, is_allocated_? oldptr : 0);
      |                              ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mclow** [comment] 2020-04-09 03:55
This is a duplicate of https://github.com/boostorg/format/issues/67

**Closed by mclow** 2020-04-09 03:55 UTC
